### PR TITLE
Fixes #51

### LINKED ISSUE #51: sigmf_validate improvements
1. Allow globstar when using like `sigmf_validate *.sigmf` to check multiple recordings simultaneously or in parallel.
2. Log/show progress if calculating checksum on huge file?

### PR DESCRIPTION
**Pull request by gregparkes**
This PR:

* Introduces globstar notation to the `sigmf_validate` command.
* Automatic support of multi-threading using `concurrent.futures`

Undergone basic testing using Pytest and linting via `black`.

### CODE REVIEW

**Comment by 777arc** [comment]
Awesome set of fixes!

**Comment by Teque5** [comment]
I made a lot of mods and added some test code, but this is working how I expect now and it looks okay to merge. I'll give you a day to respond before I merge if you want to make any other changes @gregparkes.

**Comment by gregparkes** [comment]
OK @Teque5 thanks for the changes - the 'multiple globstar' is a nice touch using the + command on argparse.

There are a number of inefficiencies in terms of speed for certain edge cases:

1. If only 1 file is selected (after all the globs), there's some overhead introduced in still producing the ThreadPoolExecutor for one task and computing asynchronously.
2. The check for no available files comes after the ThreadPoolExecutor, which again could lead to overhead.

But these are relatively small beans I'll admit.

I'm adding some slight tweaks in terms of type hints, an unused import (`Path` can be removed now), and mypy spotted a naming error (using `for error in validate_properties` where `error` is also an imported variable).

Commit incoming.

**Comment by Teque5** [comment]
Thanks for the PR @gregparkes!

**Pull request merged**
